[package]
name = "remi-hook"
version.workspace = true
edition.workspace = true

[dependencies]
remi-core = { path = "../remi-core" }

clap.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
