[package]
name = "remi-hook"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
remi-core = { path = "../remi-core" }

clap.workspace = true
directories.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dev-dependencies]
tempfile.workspace = true
